### ISSUE TITLE
Code review pugs - 67 (24/03/2020)

### ISSUE THREAD

**Issue by fivan18** [Laguna1/Newsweek-clone#5]
## Try to user `col-6` to set 50% of the width when size is smaller than 576px
https://github.com/Laguna1/Newsweek-clone/blob/c5403eaf7fb2c9eceb34f10bda84171360f32338/index.html#L28-L44

**Comment by Mindo-Joseph** [comment]
### use more descriptive class names in the css instead of .a .b .c 
### Update the live link to show the project
